version: '3.1'

services:
  db:
    image: postgres:10.23-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=librarydatabase
    ports:
      - '5432:5432'